### ISSUE TITLE
suggestion: use `squash-merge` instead of `merge`

### ISSUE THREAD

**Issue by koushiro** [paritytech/substrate-archive#203]
On the one hand, it can make the commit history clearer, and on the other hand, it can avoid problems like PR #199 that can pass the CI check but the CI check fails after the PR is merged.

**Comment by insipx** [comment]
I swear this repo is set to squash merge 😁 ![squash-merge](https://i.imgur.com/d9wqUYS.png) Not sure why it's not working as we expect. Maybe it's another option, like merge with 1 custom commit message or something?
