### ISSUE TITLE
Roadmap for the substrate-archive

### ISSUE THREAD

**Issue by satyamakgec** [paritytech/substrate-archive#242]
Sorry, I am putting up the issue related to the roadmap but I haven't found any medium where I can ask this kind of question. I am very interested to know the development roadmap of the substrate-archive or if any member of the team is available to chat I have some questions related to the development strategy. I tried to reach out on the public discord channel but not get too much attraction over there so if possible can I have someone from the team to communicate.

**Comment by insipx** [comment]
Hey @satyamakgec,

Matrix is the best place to reach us for real-time communication is the public matrix room: https://matrix.to/#/#substrate-archive:matrix.parity.io

**Comment by satyamakgec** [comment]
Thanks @insipx for the chat link, Do we have the same channel on the discord server?

**Comment by insipx** [comment]
> Thanks @insipx for the chat link, Do we have the same channel on the discord server?

we don't have a channel on the discord server/we're not active there anyway. Our preference is definitely matrix

**Comment by satyamakgec** [comment]
Okay thanks then will talk to you there.
