### ISSUE TITLE
Tracing

### ISSUE THREAD

**Issue by MilGard91** [paritytech/substrate-archive#286]
Hi guys,

I'm creating frontend UI that interacts with polkadot and I need access to some data that I can't fetch with  rpc, so I started node and also substrate-archive to get it. The problem is I need the data from state_traces but it's not filled with any data.

Command for node:
`docker run -p 9944:9944 parity/polkadot:0.8.30 --name "polkadot_node" --rpc-external --ws-external --pruning archive`

for indexer I created docker file that is getting release and runs it with config file that has chain_data_path, database_url, wasm_tracing_target

I'm new to polkadot and blockchain in general I'm probably missing something. Also maybe you have better idea of fetching votes and proposals for the account.

Thanks in advance for the response

**Comment by insipx** [comment]
Hello @MilGard91!

At what blocks are you not getting any traces? State tracing is only supported on runtime versions v8.27 and above, so if you are not on those then you will not get any traces. For runtime v0.9.XX a release is being cut to include support for those runtime versions today or tomorrow.

**Comment by MilGard91** [comment]
Hi @insipx!

Thanks for the reply, correct me if I understood wrong but I was missing --wasp-overrides on node and `folder` in config for indexer that will point to it so the state_traces would be inserted in the db.

**Comment by insipx** [comment]
Yeah, those are also required for tracing! Closing this for now then
