### ISSUE TITLE
can we use substrate-archive to backup and restore chain? and  restore to specific block high

### ISSUE THREAD

**Issue by baidang201** [paritytech/substrate-archive#302]

**Comment by insipx** [comment]
Hey! cool question.

 while theoretically I suppose we could store all the chain state in substrate archive, be very careful about it, change the code to verify everything, and then use it to restore a substrate database, I think it would be much easier to go about it differently. The workflow with archive would look like rocksdb -> sql and to restore sql -> rocksdb. Whereas, rocksdb already contains [snapshotting](https://github.com/facebook/rocksdb/wiki/Basic-Operations#snapshots). So I think it would be easier to just create a tool that only does backups when users need them separate from archive.

**Comment by baidang201** [comment]
thank you
