### ISSUE TITLE
update nightly in workflow file

### ISSUE THREAD

**Issue by insipx** [paritytech/substrate-archive#316]
Once this bug: https://github.community/t/failed-sending-data-to-the-peer-connection-died-tried-5-times-before-giving-up/189130 is fixed, our workflow file for unit tests should be updated from `nightly-2021-07-05` back to just `nightly`

**Comment by dvdplm** [comment]
Is there a rustc bug for this? Would be good to have a ref to that too.

**Comment by insipx** [comment]
Yeah, just found an issue opened in the crates.io repo: https://github.com/rust-lang/crates.io/issues/3782
