### ISSUE TITLE
Always raise too many open files error 

### ISSUE THREAD

**Issue by freehere107** [paritytech/substrate-archive#407]
System: mac os  Monterey

I try run https://github.com/paritytech/substrate-archive#archive-fails-to-start-with-a-too-many-open-files-error with
```
 ulimit -u 90000 
```
and ``` ulimit -a ```

```
-t: cpu time (seconds)              unlimited
-f: file size (blocks)              unlimited
-d: data seg size (kbytes)          unlimited
-s: stack size (kbytes)             8176
-c: core file size (blocks)         0
-v: address space (kbytes)          unlimited
-l: locked-in-memory size (kbytes)  unlimited
-u: processes                       2666
-n: file descriptors                90000

```
When i run ``cargo run --release --bin polkadot-archive``

always raise error 

```Error: IO error: While opening file for sequentially read: .../polkadot_archive/db/full/14002628.log: Too many open files```

**Comment by freehere107** [comment]
One thing may be special on my side, my db file uses https://dot-rocksdb.polkashots.io

**Comment by dvdplm** [comment]
What does running `launchctl limit` show you? It outputs the system level open files cap (soft/hard limits). Do increase the limit you need to raise both the system level limits and the shell level limits (set by `ulimit`).

You can also check the current kernel settings with `sysctl -a | grep maxfiles` but I *think* that those settings are ignored on recent versions of macos, worth a try with something like `sudo sysctl kern.maxfiles=640000 kern.maxfilesperproc=280000` though.

If that doesn't work you have to set up a `.plist` file and use `launchctl` to load it.

**Comment by insipx** [comment]
> One thing may be special on my side, my db file uses https://dot-rocksdb.polkashots.io

Using polkashots snapshot will result in an incomplete postgres database. Although I guess this may be desirable in some circumstances, you'll probably miss some blocks and storage entries before a certain point, and there may be large gaps. It's recommended to run against a fresh node with `--pruning=archive`. afaik polkashots prunes their snapshots

**Comment by freehere107** [comment]
@dvdplm Hi, thank you reply. I try running  ``sudo sysctl kern.maxfiles=640000 kern.maxfilesperproc=280000``

and also set ``limit.maxfiles.plist``


Run ```launchctl limit``` 

```
	cpu         unlimited      unlimited
	filesize    unlimited      unlimited
	data        unlimited      unlimited
	stack       8372224        67092480
	core        0              unlimited
	rss         unlimited      unlimited
	memlock     unlimited      unlimited
	maxproc     2666           4000
	maxfiles    64000          524288
```

and  ``sysctl -a | grep maxfiles``

```
kern.maxfiles: 524288
kern.maxfilesperproc: 64000
```

But still  raised ``Too many open files`` error 

This doesn't work

**Comment by dvdplm** [comment]
@freehere107 I am sorry you're having issues and I'm sorry Apple isn't making this as easy as it should be. On Linux it's much easier.

**Comment by freehere107** [comment]
@dvdplm ok, Thank you~
