### ISSUE TITLE
How to display data in ReactJS using GraphQL stored by archiver into postgres

### ISSUE THREAD

**Issue by farazahmadvaival** [paritytech/substrate-archive#444]
Hi,

I am able to run archiver and it is persisting data into postgres. I am quite confused about how can i use this data to show on frontend i.e RactJS or angular. How to parse the data to human friendly.

**Comment by yangmiok** [comment]
<img width="858" alt="Screen Shot 2022-03-08 at 6 29 35 PM" src="https://user-images.githubusercontent.com/7039266/157218476-89301cc6-c8bb-4e8a-bc1e-db91daee5a77.png">

**Comment by farazahmadvaival** [comment]
exactly the same situation to me. I want to display extrincs details and accounts information on the front end but am unable to find it anyway.

**Comment by yangmiok** [comment]
I want to search all transactions of a address

**Comment by yangmiok** [comment]
Tell me if you find a way

**Comment by yangmiok** [comment]
I've found a solution for office [](https://github.com/paritytech/desub)

**Comment by farazahmadvaival** [comment]
Thank you for your help @yangmiok. So nice of you.

**Comment by yangmiok** [comment]
I am trying to learn how to use it [https://github.com/paritytech/desub](url) ,do you know how to run it?

**Comment by yangmiok** [comment]
![Uploading Screen Shot 2022-03-09 at 4.26.09 PM.png…]()

**Comment by yangmiok** [comment]
<img width="1365" alt="Screen Shot 2022-03-09 at 4 27 32 PM" src="https://user-images.githubusercontent.com/7039266/157402165-f604ef00-8594-4983-897c-5704d908e857.png">

**Comment by yangmiok** [comment]
I am trying to load blocks for Postgres ,But it the blocks is null , I do not know why.

**Comment by farazahmadvaival** [comment]
are you able to view the blocks in the database?

**Comment by farazahmadvaival** [comment]
I am using Hasura (https://hasura.io/) on top of postgres to expose data as GraphQL.

**Comment by yangmiok** [comment]
> are you able to view the blocks in the database?

yes

**Comment by yangmiok** [comment]
> I am using Hasura (https://hasura.io/) on top of postgres to expose data as GraphQL.

what is the result ?

**Comment by yangmiok** [comment]
how to change the data format in the Postgres :0x8EBA1D8F67B6438FA90B6C418082D8CA136360DFE7475257C93F39FD9AE762A9

**Comment by yangmiok** [comment]
[https://github.com/playzero/substrate-graph](url)

**Comment by yangmiok** [comment]
which project you use 

1.https://github.com/substrate-developer-hub/substrate-node-template

2.https://github.com/paritytech/substrate



I try 1 success but the 2 fail.

**Comment by yangmiok** [comment]
what about this project

https://github.com/subscan-explorer/subscan-essentials

have you used it?

**Comment by farazahmadvaival** [comment]
> which project you use
> 
> 1.https://github.com/substrate-developer-hub/substrate-node-template
> 
> 2.https://github.com/paritytech/substrate
> 
> I try 1 success, but the 2 fail.

I am building a blockchain using substrate and frontier. I have to run smart contracts built for Ethereum. I have built the chain and it is working perfectly. Now I have to build an explorer for which I tried substrate archiver to dump data into the database. But the issue is with the parsing of data. I was unable to extract the data to display into the frontend app. I tried many other indexers but finally, I tried with squid. (https://docs.subsquid.io/). It has good documentation. you can check this tool.

**Comment by farazahmadvaival** [comment]
> what about this project
> 
> https://github.com/subscan-explorer/subscan-essentials
> 
> have you used it?

I tried with subscan too but it did not work with the custom blockchain.

**Comment by yangmiok** [comment]
> into


good.

```
root@ip-172-31-5-141:~/squid-template# node -r dotenv/config lib/processor.js
Prometheus metrics are served at port 45609
Last block: 93294, mapping: 30 blocks/sec, ingest: 195 blocks/sec, eta: 45m, progress: 1%
Last block: 117895, mapping: 76 blocks/sec, ingest: 220 blocks/sec, eta: 46m, progress: 1%
Last block: 137020, mapping: 114 blocks/sec, ingest: 206 blocks/sec, eta: 46m, progress: 1%
Last block: 149469, mapping: 112 blocks/sec, ingest: 174 blocks/sec, eta: 48m, progress: 1%
Last block: 162912, mapping: 111 blocks/sec, ingest: 307 blocks/sec, eta: 56m, progress: 1%
Last block: 177482, mapping: 110 blocks/sec, ingest: 240 blocks/sec, eta: 58m, progress: 2%
Last block: 194629, mapping: 115 blocks/sec, ingest: 214 blocks/sec, eta: 1h 0m, progress: 2%
Last block: 203302, mapping: 113 blocks/sec, ingest: 118 blocks/sec, eta: 1h 4m, progress: 2%
```

**Comment by farazahmadvaival** [comment]
This looks subsquid processor part. you can check for subsquid indexer part if you want to connect your custom chain. 

https://docs.subsquid.io/key-concepts/architecture#squid-archive

**Comment by yangmiok** [comment]
> This looks subsquid processor part. you can check for subsquid indexer part if you want to connect your custom chain.
> 
> https://docs.subsquid.io/key-concepts/architecture#squid-archive

thank you. So nice of you.
