### ISSUE TITLE
ReadOnlyFilesystem Error

### ISSUE THREAD

**Issue by Bui-Christopher** [paritytech/substrate-archive#474]
First time using substrate-archive, trying to set up polkadot archiving as an example. 

I understand wiki/tutorial is a outdated. Ran a solution from [this](https://github.com/paritytech/substrate-archive/issues/423) issue.

1. Run `docker-compose up -d` to start postgres and pgadmin
2. Run `DATABASE_URL=postgres://postgres:123@localhost:6432/local_chain_db sqlx database create` in substrate-archive/src to create the database.
3. Run `DATABASE_URL=postgres://postgres:123@localhost:6432/local_chain_db sqlx migrate run' in substrate-archive/src` to create the tables.
4. Run `cargo run --release -- -c archive.toml in bin/node-template-archive/` to start indexing. Keep in mind to modify the archive.toml configs.

On the last step I received an error:
```Error: Failed to create RocksDB directory: `Os { code: 30, kind: ReadOnlyFilesystem, message: "Read-only file system" }`.```

**Comment by insipx** [comment]
Hey @Bui-Christopher,

Not sure this is coming from archive, have you checked the directories in `archive.toml` to see if the user you are starting archive with has write permission?

**Comment by Bui-Christopher** [comment]
Thank you for responding quickly! The issue was a mistake on my end. Modified the archive.toml config incorrectly.
