### ISSUE TITLE
Raise the fdlimit if we detect `too many open files`

### ISSUE THREAD

**Issue by insipx** [paritytech/substrate-archive#88]
This crate: https://github.com/paritytech/fdlimit could help quell the common issue users run into when starting substrate archive for the first time, the `too many open files` error. This error that occurs as a result of the secondary rocksdb database requiring all files of the primary database to be kept open.

**Comment by liuchengxu** [comment]
Sounds like we also want to raise a warning like https://github.com/paritytech/substrate/pull/6956?

**Comment by insipx** [comment]
yeah, a warning with some context would be ideal

**Comment by liuchengxu** [comment]
@insipx Hi, please take a look at #94, I simply borrowed https://github.com/paritytech/substrate/pull/6956, let me know if you want to display more context.
